### ISSUE TITLE
parcours.cpp

### ISSUE THREAD

**Issue by LiaOkami** [LiaOkami/RamaPieceAS2#1]
parcours.cpp souffre de divers problèmes qu'il faudrait corriger au plus vite.

1) Le fichier ne compile pas. Il a pour le moment été retirer de la solution "Opti", il faudra le ré-ajouter pour tester. La plupart des erreurs proviennent d'une mauvaise manipulation des vecteurs (ne pas oublier que Ramapiece.getPiece() renvoie un pointeur vers un vecteur).

L'ajout de documentation pour Ramapiece et la complétion de ce dernier permettent de tester efficacement les algorithmes, ne pas hésiter à regarder l'exemple situé dans le main.

2) Le fichier est assez grand et confus. Je suggère, une fois le premier point corrigé, de faire un fichier par parcours (avec les fonctions accompagnant chaque parcours dans son fichier correspondant). Il est ensuite possible de garder parcours.h pour tous les .cpp, qui n'aura besoin de contenir que les prototypes des fonctions à appeler, donc une seule par fichier.

**Comment by LiaOkami** [comment]
Le premier point est corrigé par #3. Les commentaires devraient être déplacés dans le header pour les fonctions concernées, et le second point est toujours nécessaire.

**Comment by stephAc** [comment]
Résolu par c1bd507ac1b23ae86fef08d30a23bf3d6b1c35b1
